spring.application.name=backend
spring.security.oauth2.client.registration.google.client-id=463537441917-icrrho3efiqmcaf9245t5tplheqtgol2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
